#!/var/lib/python/python-q4

from twisted.web import server, resource, static
from twisted.internet import reactor, ssl
import os
import tempfile
import sys
import prctl

if len(sys.argv) != 3:
    print "Usage: ./local_webserver certificate.x509 privatekey.priv"
    exit(1)

CERT = sys.argv[1] 
PRIV = sys.argv[2] 

HTML = """
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Government of Caltopia Email Server</title>

    <style type="text/css">
      .form-signin {
        text-align: center;
        width: 300px;
        margin: 90px auto 0;
        padding: 19px 29px 29px;
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

      .form-signin h2 {
          font-family: 'Lucida Sans Unicode';
      }

      .cal-title {
          margin: 40px auto 0;
          min-width: 500px;
          text-align: center;
      }

      .info {
          background-color: #A9DAFC;
          border: 1px solid #333;
          padding: 10px;
          font-size: 20px;
          width: 400px;
          margin: 50px auto 0;
      }

      body {
          background: url("seal.png") white no-repeat center 50px;
          font-family: 'Lucida Sans Unicode';
      }

      .button {
         border-top: 1px solid #96d1f8;
         background: #65a9d7;
         background: -webkit-gradient(linear, left top, left bottom, from(#3e779d), to(#65a9d7));
         background: -webkit-linear-gradient(top, #3e779d, #65a9d7);
         background: -moz-linear-gradient(top, #3e779d, #65a9d7);
         background: -ms-linear-gradient(top, #3e779d, #65a9d7);
         background: -o-linear-gradient(top, #3e779d, #65a9d7);
         padding: 5px 10px;
         -webkit-border-radius: 8px;
         -moz-border-radius: 8px;
         border-radius: 8px;
         -webkit-box-shadow: rgba(0,0,0,1) 0 1px 0;
         -moz-box-shadow: rgba(0,0,0,1) 0 1px 0;
         box-shadow: rgba(0,0,0,1) 0 1px 0;
         text-shadow: rgba(0,0,0,.4) 0 1px 0;
         color: white;
         font-size: 14px;
         font-family: 'Lucida Sans Unicode';
         text-decoration: none;
         vertical-align: middle;
         }
      .button:hover {
         border-top-color: #28597a;
         background: #28597a;
         color: #ccc;
         }
      .button:active {
         border-top-color: #1b435e;
         background: #1b435e;
         }
    </style>

  </head>

  <body>
      <h2 class="cal-title">Government of Caltopia Email Server</h2>



      <form class="form-signin" name="caltopia_email_form" method="post">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" class="input-block-level" placeholder="Login" name="caltopia_email_login" />
        <input type="password" class="input-block-level" placeholder="Password" name="caltopia_email_password" />
        <br/><button class="button" name="caltopia_email_submit" type="submit">Sign in</button>
      </form>

       <!-- INFO -->

    </div>
    </div> 

  </body>
</html>
"""

class Server(resource.Resource):
    isLeaf = False
    def getChild(self, name, request):
        if name == "seal.png":
            return resource.Resource.getChild(self, name, request)
        return self

    def render_GET(self, request):
        return HTML

    def render_POST(self, request):
        print request.args
        return "<HTML>OFFLINE... OR ARE WE</HTML>"


if not prctl.cap_effective.net_bind_service:
    print "ERROR: I must be invoked via `./local_webserver`, not via `python local_webserver`!"
    exit(1)

root = Server()
root.putChild("seal.png", static.File("/home/neo/q4/local_webserver/seal.png"))

site = server.Site(root)
reactor.listenSSL(443, site, ssl.DefaultOpenSSLContextFactory(PRIV, CERT))
reactor.run()
